resolves #146 remove PDB files instead of truncating them (#149)
This commit fixes 'error CS0045: Unexpected error creating debug information file' that occurs when UE4 builds Engine/Intermediate/Build/BuildRules/UE4Rules.dll on Windows